### PR TITLE
A number of updates

### PR DESCRIPTION
**Pull request by mikeferguson**
- Actually use effort field we added to trajectory (#2)
- Always use the last trajectory point
- Add a "parallel" parameter which will allow us to have the new use case:
  - two joints (the two fingers), move equal amounts, but the command should be the sum of their individual commands. 
- Make some stupidly long lines slightly less stupidly long

### CODE REVIEW

**Comment by mikeferguson** [comment]
@davetcoleman if you get a chance, make sure this doesn't break your setup -- certainly post if it does.

**Comment by isucan** [comment]
Looks good to me. Feel free to merge (@davetcoleman it would be great if you could try this)

**Comment by mikeferguson** [comment]
ok, now I've even tested the parallel stuff (I couldn't quite get to that before) with pick'n'place issues

**Comment by davetcoleman** [comment]
Thanks for the fixes, my tests so far seem to work but the other attached collision objects issue was holding me back from confirming this

**Pull request merged**
