### PR TITLE
Allow simple controller manager to ignore virtual joints without failing

### PR DESCRIPTION
**Pull request by davetcoleman**
The MoveIt Simple Controller Manager currently fails when a FollowJointJointTrajectoryController receives a request that includes a virtual joint. However, there are cases such as a biped robot where a virtual joint is included in a planning group that sends requests to the controller. While it is ok for the trajectory controller to ignore the virtual joint, it should not fail. This PR instead makes it just issue a warning.

@mmurooka

### CODE REVIEW

**Comment by isucan** [comment]
+1

**Comment by mikeferguson** [comment]
LGTM

**Comment by mikeferguson** [comment]
I was going to merge this, given that I am still listed as the maintainer of this package. However, I see that not only have I lost commit rights, I have been removed entirely from the project, again, without any notice or explanation.

@isucan Please find a new maintainer and update the package.xml, as I will no longer be contributing to MoveIt, or any software in the ros-planning group.

**Comment by isucan** [comment]
I will defer to @sachinchitta

**Comment by sachinchitta** [comment]
@mikeferguson - your push access to MoveIt! plugins has been restored. Your contributions are appreciated - this was a mistake on my part while cleaning up the teams. Let me know if your push access is not working.

**Pull request merged**
