### PR TITLE
set of fake controllers (#21)

### PR DESCRIPTION
**Pull request by rhaschke**
Backport of #21 to indigo as requested by @v4hn.
Adapted .travis.yml to build against indigo distro.

### CODE REVIEW

**Comment by v4hn** [comment]
I suppose by default this request does not change any behavior in the fake_controller_manager, is that right?

**Comment by rhaschke** [comment]
> I suppose by default this request does not change any behavior in the fake_controller_manager, is that right?

The default fake controller becomes the interpolating one, instead of the "last point" one. Is that what you were asking for?

**Comment by rhaschke** [comment]
@v4hn: Well spotted typo!

**Comment by v4hn** [comment]
I just tried to use it with the default pr2 config :)
Once this passes, feel free to merge all three requests

**Pull request merged**
